site_name: 随笔
pages:
- 主页: "index.md"
- 提问的智慧: "study/how2ask.md"
- Python:
  - Python: "python/python.md"
  - PyGame: "python/pygame.md"
  - Virtualenv: "python/virtualenv.md"
  - Matplotlib: "python/matplotlib.md"
  - Tensorflow: "python/tensorflow.md"
- Tool:
  - Atom: "tool/atom.md"
  - Sdkman: "tool/sdkman.md"
  - Graphviz: "tool/graphviz_.md"
- Daily:
  - review2017: "daily/review2017.md"
  - plan2018: "daily/plan2018.md"
- Book:
  - 如何阅读一本书: "book/how_to_read_a_book.md"
  - 复盘: "book/fupan.md"
  - 极简主义: "book/极简主义.md"
  - 解决问题最简单的方法: "book/解决问题最简单的方法.md"
- 关于: "about.md"
#theme: readthedocs
