site_name: 随笔
pages:
- 主页: "index.md"
- 提问的智慧: "study/how2ask.md"
- Python:
  - Python: "python/python.md"
  - Tkinter: "python/tkinter.md"
  - Virtualenv: "python/virtualenv.md"
  - Matplotlib: "python/matplotlib.md"
- Tool:
  - Atom: "tool/atom.md"
  - Sdkman: "tool/sdkman.md"
  - Graphviz: "tool/graphviz.md"

- 关于: "about.md"
#theme: readthedocs
