site_name: 随笔
pages:
- 主页: "index.md"
- 提问的智慧: "study/how2ask.md"
- Python:
  - Tkinter: "python/tkinter.md"
  - Jieba: "python/jieba.md"
  - Virtualenv: "python/virtualenv.md"
  - Matplotlib: "python/matplotlib.md"
- 其它:
  - Angular1: "other/angular1.md"
  - Angular2: "other/angular2.md"
  - Atom: "other/atom.md"
  - Elasticserach: "other/elasticserach.md"
  - Elk: "other/elk.md"
  - Gitlab: "other/gitlab.md"
  - Hadoop: "other/hadoop.md"
  - Hbase: "other/hbase.md"
  - Java: "other/java.md"
  - Jhispter: "other/jhispter.md"
  - Mongodb: "other/mongodb.md"
  - Mysql: "other/mysql.md"
  - Nexus: "other/nexus.md"
  - Nginx: "other/nginx.md"
  - Python: "other/python.md"
  - Redis: "other/redis.md"
  - Sdkman: "other/sdkman.md"
  - Svn: "other/svn.md"
  - Three: "other/three.md"


- 关于: "about.md"
theme: readthedocs
