site_name: 随笔
pages:
- 主页: "index.md"
- 提问的智慧: "study/how2ask.md"
- Python:
  - Python: "python/python.md"
  - Python编码模式: "python/python编码模式.md"
  - PyGame: "python/pygame.md"
  - Virtualenv: "python/virtualenv.md"
  - Matplotlib: "python/matplotlib.md"
  - Tensorflow: "python/tensorflow.md"
- KOL:
  - 抖音: "kol/douyin.md"
  - 自明星就是超级IP秦刚: "kol/自明星就是超级IP秦刚.md"
- Tool:
  - MMD: "model/mmd.md"
  - Atom: "tool/atom.md"
  - Sdkman: "tool/sdkman.md"
  - Graphviz: "tool/graphviz_.md"
- Daily:
  - review2017: "daily/review2017.md"
  - plan2018: "daily/plan2018.md"
- Book:
  - 如何阅读一本书: "book/how_to_read_a_book.md"
  - 断舍离: "book/断舍离.md"
  - 简约之美: "book/简约之美.md"
  - 极简主义: "book/极简主义.md"
  - 解决问题最简单的方法: "book/解决问题最简单的方法.md"
  - 有效管理的5大兵法: "book/有效管理的5大兵法.md"
  - 复盘: "book/fupan.md"
- Fiction:
  - 小说的骨架: "novel/小说的骨架.md"
- 关于: "about.md"
theme: readthedocs
