site_name: 随笔
pages:
- 主页: "index.md"
- 提问的智慧: "study/how2ask.md"
- Python:
  - Python: "python/python.md"
  - Tkinter: "python/tkinter.md"
  - Jieba: "python/jieba.md"
  - Virtualenv: "python/virtualenv.md"
  - Matplotlib: "python/matplotlib.md"
- Web:
  - Angular1: "web/angular1.md"
  - Angular2: "web/angular2.md"
- XD:
  - Elasticserach: "bigdata/elasticserach.md"
  - Elk: "bigdata/elk.md"
  - Hadoop: "bigdata/hadoop.md"
  - Hbase: "bigdata/hbase.md"
- Tool:
  - Atom: "tool/atom.md"
  - Gitlab: "tool/gitlab.md"
  - Sdkman: "tool/sdkman.md"
  - Svn: "tool/svn.md"
  - Graphviz: "tool/graphviz.md"
  - Nexus: "tool/nexus.md"
- Java:
  - Java: "java/java.md"
  - Jhispter: "java/jhispter.md"

- DB:
  - Mongodb: "db/mongodb.md"
  - Mysql: "db/mysql.md"
  - Redis: "db/redis.md"

- Other:
  - Nginx: "other/nginx.md"
  - Three: "other/three.md"


- 关于: "about.md"
#theme: readthedocs
